sudo: required
dist: xenial
before_install:
- sudo apt update -y
- pip install --user awscli
install:
- mkdir -p ~/.local/lib && mkdir -p ~/.local/bin
- git clone https://$PV_OAUTH_TOKEN@github.com/polyverse-security/pv ~/.local/lib/pv
- ln -s ~/.local/lib/pv/pv ~/.local/bin/pv
script:
- pv aws ecr-login
- "./build.sh || travis_terminate 1;"
- "./test.sh || travis_terminate 1;"
- "./publish.sh || travis_terminate 1;"
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - secure: i4i2f/OlJ9m0Gewctnbkvn+M0HN8Rzrw11mLpWelNbctFw7QRUuLsQXDmq/LcyS+kdcws5/Fwfo/EBRZIVH/t4vf9+6gzvvWLUFoZDbboGbP7e/bqe0gFGxyJUZwI3hrqar/l5JYRKz+Tl1eZM0s08PPJvltrv1sx9Dr4h8PHMvJUjQQq0ZQWY+RR+1Z/wZ8O83pBq/IL1IpkJVW2YRmzaNwSTnd/EQKfP2hv+9E96tTwfNotG4lheg5+iqSLzKRDcZWtYiOaFn201avYajk9uBHTVu0UHXibpuilXxmfSloTumZRD05ojkbejBPm5hmHmQGVQblBBMOztw6c6Ub4g5w8E4fDZKfqUSAiNGTjcUdfx3rvt0LaWxrPZ7S6chcSAL++uTZyTw50ND0NtG+DCfhigc11umxumCGSnDzMA+/O48ceAzdH9T0VLd0oDceX5+w/JNquYuz8dyUnfRXBqV+/Ux9OdBZWvjS8CiwzY5XM3VLJOApSJTewMXHImMGBMgYlglY8NAI+P5EvtLC/S6OUQWvget9SDRWBe2fY0RMLd+OE/J6e388iVYwby8BJ9iiqqkiCrYIzLO/xPsIo6HjghYDm+Rt3YH62mP0YwWhl68z1GqM/8aovGgw5adCatwrbIRbfcNyJU7YotN9agTZxuA2o3m+ImxyuRllFUY=
