sudo: required
dist: xenial
before_install:
- sudo apt update -y
- pip install --user awscli
install:
- mkdir -p ~/.local/lib && mkdir -p ~/.local/bin
- git clone https://$PV_OAUTH_TOKEN@github.com/polyverse-security/pv ~/.local/lib/pv
- ln -s ~/.local/lib/pv/pv ~/.local/bin/pv
script:
- pv aws ecr-login
- "./build.sh || travis_terminate 1;"
- "./test.sh || travis_terminate 1;"
- "./publish.sh || travis_terminate 1;"
env:
  global:
    secure: m9yNl129Weebzhv47CzbdcUhchrjLbmY7pUZgAzNgaF0MhL9rULYmcWL2O2cP2BH3ouv4HXJpCi1gtclN934ax8Zji+JBS1uFhm1cEG+so8UFqopDQX3haOV/8ARG99qi4GZB7Xwnkf6xlTtrcEhtNQEtfX3f8zqL8QlKzMoPA4MRDSmo7IR5PRcJHAclKrQVinPscFFNNBZsdYQUSD7yvBlA5ViBqO9QlOLrLyfDpLBZZGpwB+Vls95j+rRqJ6SIqJnlt0B7o3QF6HUU0EOB5hy//r5ysFDxJbeWBLVtodxBOz1Zko0k6DNhmgTStq7rbjOLhZ3aF2G47KWtFFL0GPHsABYY6ZypMBH2J+YU/Ktf5Y0nXo4B6RR//ZJXB3+FDcS4bK7AuKjzV8EFK+2Gq1frCANJw6ve74miKFdSL5+En8zrmtMU679pUI+DAjzntaEi2fgQCLLSWiq75NPlgyXzEBsFXAXw2jeQEuLlB1gGu6t6FaVr5L/9OmZx82uKf0tJGNyNicNcFqo4InuXzBAAOe4J9be7Ljsa5TflpkP9vnaDcXSqDulOuWgNTCzrfkHJ7WnTkdrOutby6zmMoOuBRaxLv7uF4HBFh+HvjFdd3qJYLyPRh2vqKcR80IBh2YdFB9GCohobPBcmId28/vcBZo668H9CVBeviCew14=
