sudo: required
dist: xenial
before_install:
- sudo apt update -y
- pip install --user awscli
install:
- mkdir -p ~/.local/lib && mkdir -p ~/.local/bin
- git clone https://$PV_OAUTH_TOKEN@github.com/polyverse-security/pv ~/.local/lib/pv
- ln -s ~/.local/lib/pv/pv ~/.local/bin/pv
script:
- pv aws ecr-login
- "./build.sh || travis_terminate 1;"
- "./test.sh || travis_terminate 1;"
- "./publish.sh || travis_terminate 1;"
env:
  global:
  - secure: wnjl0XqMRHWsw2o5n6PD+lUXWou3iGPqsEbZwNDmYXyKlWvzfN7Hxz//Z+n+Q9+dfMfSU+MuOPYtdcPH0EaGHhJpH3oe4jfzrPx3kg8KMr0ywjG6/zYm6PlCdEk7ZLGcytw4TSikhZfgCrCjMh7z4Rk4eq37G57MHSJobw3z9ecWspoRYDfhm/11H2vIHVbgmw9AvFCu5TVbXMKpoHI7+iOvGrhm6/Aq//M0l6tSXs/EUbkqgz4wG2j995EhNNi92EC9xXyxcfufsKaq/A7JlrOeq58jI/bg7mRreEzE+zpqoEMm07ym9YVq/ZDBd0cLYnQrBNKzAzVYl+lbc0Q20L8apE+Foz6Mx06CF9OhROQfedhla/wfzgbHxEgW06L+WOLvPYkaoKM7TSP+XU3lfw/ZkMx02lguTeWvMKXEqFKT+fYOKIJh83OEmrb1YOt0yhO+dupgkyq2wwIKOVuMqQp5fN0xCBBE3YcItPMLttmYo5xq5V+XQq5gMwJ+0Iuf7tLsXDEZlTY16cuK+Tcy/nVkuz4ZFo3fjmMQ4EQyVhaa1UL0PoNDy4CZjuSHcAzwrPq9RNkwL1Lf9UqZye+B2GrY00NV+WW2MUimG7uqlb5eHKCcauFgxwFFCGgPqdL3nWh20Lzk8AhEhjIWir7FpVMJl0frxzA2t49I8jdszF4=
  - secure: M50VGS2/OOovbADi+81uNX0FeZifIyxUAvZsbyML7K0WqvYKXLAivur80PvPEO9lAG0zbmTN0Qu8fFT4z8uUJbrJAZiDf4+2GnsJ6kjBsLr8wTJ4H8OemPO84F0W5/2dC35QBqZF/cdP/SvuzZTCMfw9823QVjdke3n5LZWk4Nab4e/wsHHBl+6WrZAVcOXPgrNYs4VFAJijB1bLokAcMIkIWBFMhaPamIkTM3IVxciHjhephL0hRacHMWMAGaM6BSCajv1FZYlPHaF5EJQDTJdtU5h4IecFvJWYqH8QA7nGfZtd8/1LDlvOnpvkh7YS5Z1qo6iE84wHceGG8pOE/L9yHG4XYm+QIf71QcnfRuQmTdSLFuyJO8OkvdPVnZpZ7GNDW1sUp6vyfG3LuYqCmT05DUsdw4FVChmiwOvwMZqO5E9fpA9OOwaO5KwizAnXP2uxmDNhkgP9kxHN+XamJ6QKNV3xMAXGLnsyqYXXMVmvE+tA9aRqfYA8GgSVDgUgJW0/MPsva4TFTU0YtDzA9KGgG3cReQX2n8HqFbdREApOZS2J296Zv1+vgvV7eMGRHjxDKAYLE7s+By10tBJBzAMqc/4vZe7jFbXI6OJuBmKIhMz48Jtib316I0+IvixpXr8BhMnL231Zpow7hXpsGXbC7r+YSlR65JWhI5wtHPg=
